drop table if exists users CASCADE;
create table users
(
    user_id varchar(20) not null,
    password varchar(50) not null,
    name varchar(20) not null,
    email varchar(50) not null,
    primary key (user_id)
);

drop table if exists articles CASCADE;
create table articles
(
    article_id bigint generated by default as identity,
    title varchar(50) not null,
    contents varchar(255) not null,
    user_id varchar(20) not null,
    created_date timestamp not null,
    primary key (article_id),
    foreign key (user_id) references users(user_id)
);

